global:
  scrape_interval: 5s  # Как часто собирать метрики (по умолчанию 15s)

scrape_configs:
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8222']